// Generated by CoffeeScript 1.5.0
(function() {
  var browser, casper, myAccount;

  casper = require('casper');

  browser = casper.create();

  myAccount = "http://localhost:3000";

  browser.start(myAccount);

  browser.then(function() {
    return this.test.assertTextExists('Hello');
  });

  browser.thenEvaluate(function() {
    return BDD.startTask('testing');
  });

  browser.wait(1000);

  browser.thenEvaluate(function() {
    return BDD.stopCurrentTask();
  });

  browser.then(function() {
    this.test.assertTextExists(2);
    return this.test.assertTextExists('testing');
  });

  browser.run(function() {
    return this.exit();
  });

}).call(this);
